name: Jenkins CI Trigger

on:
  push:
    branches:
      - sarra-bennour  # Branche à surveiller (ajuste si nécessaire)

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins job
        run: |
          curl -X POST "https://5237-2c0f-4280-0-908e-681e-aaac-8b0c-577d.ngrok-free.app/job/project-devops/build" \
          --user "admin:115858233081fdd33fa3766e6978a87d3c"
