version: '3.8'

services:
  # Service de l'application Spring Boot
  kaddem-app:
    image: sarrahsahli/kaddem:latest
    container_name: kaddem-app
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - kaddem-network
    depends_on:
      - mysql-db

  # Service MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
      MYSQL_USER: kaddem
      MYSQL_PASSWORD: kaddem
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kaddem-network

volumes:
  mysql-data:

networks:
  kaddem-network:
    driver: bridge
