name: Jenkins CI Trigger

on:
  push:
    branches:
      - sarra-bennour  # Branche à surveiller (ajuste si nécessaire)

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins job
        run: |
          curl -X POST "https://6808-2c0f-4280-3071-67dc-e165-d1f8-4dd9-7d7f.ngrok-free.app/job/projet-devops/build" \
          --user "admin:115858233081fdd33fa3766e6978a87d3c"
