name: Jenkins CI Trigger

on:
  push:
    branches:
      - noussa

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins job
        run: |
          curl -X POST "https://edcc-197-238-231-61.ngrok-free.app/job/Kaddem/build" \
          --user "noussa:1132a14e099816b2788a12d252248031eb"
